### PR TITLE
Add DY positivity using vrap

### PR DESCRIPTION
**Pull request by scarlehoff**
Add positivity on top of #139

### CODE REVIEW

**Comment by scarlehoff** [comment]
@enocera a few questions regarding positivity:
- Can I just run vrap at LO? (since we are just worried about the luminosity, right?)
- In principle the infamous jacobian or factors like 54.4 should not matter but where is the actual formula for the positivity fktable? (so that at least the dimensions are comparable). In the 3.0 paper there's only "proportional to"
- Same for the ECM that was used for the computation? I cannot find it in the 3.0 paper nor in the previous one.

I think that's all I will need in order to compare them with the old ones.

**Comment by enocera** [comment]
> @enocera a few questions regarding positivity:
> 
> * Can I just run vrap at LO? (since we are just worried about the luminosity, right?)

I don't think so. Look for example at Eq. (6.2) in https://arxiv.org/pdf/hep-ph/0312266.pdf. What we call, e.g., `POSDYU` the following quantity:
$$\frac{d^2\sigma_{u\bar u}}{dMdy}=\frac{4\pi\alpha^2}{9M^3} \int dx_1 dx_2 N^{\gamma, Z} \frac{d\sigma_{u\bar u}^{\gamma,Z}}{dy} \mathcal{L}_{u\bar u}$$.

I'd say that 
$$\frac{d\sigma_{u\bar u}^{\gamma,Z}}{dy}=1+\mathcal{O}(\alpha_s)$$
depends on the perturbative order. Wouldn't you say the same?
> * In principle the infamous jacobian or factors like 54.4 should not matter but where is the actual formula for the positivity fktable? (so that at least the dimensions are comparable). In the 3.0 paper there's only "proportional to"

Somewhere in APFEL... Let me check.
> * Same for the ECM that was used for the computation? I cannot find it in the 3.0 paper nor in the previous one.

From `POS.cc` in `buildmaster/filters` I read:
$\sqrt{s}=q2pos/\tau$
with 
$q2pos=5$ GeV 
$\tau=x_{\rm min}\cdot x_{\rm max}$ where $x_{min}=0.01$ and $x_{max}=0.9$

**Comment by scarlehoff** [comment]
Can we merge this. Also, can you fix the conflicts that are coming from the rebase on the branch @AleCandido ?

**Comment by AleCandido** [comment]
> Can we merge this. Also, can you fix the conflicts that are coming from the rebase on the branch @AleCandido ?

I can solve for `poetry.lock` (trivial -> rerun `poetry update`) and for `yad.py` (just one import). But for `vrap.py` it would be better if you do it yourself @scarlehoff

**Comment by scarlehoff** [comment]
Ok, fix those two and I'll fix the other.

**Comment by AleCandido** [comment]
> Ok, fix those two and I'll fix the other.

How can I rebase preserving a conflict?

**Comment by scarlehoff** [comment]
You can always say the conflict was solved even if it wasn't. I'll have a look at `vrap.py` afterwards.

**Comment by AleCandido** [comment]
Actually, rebase was straight, I just had to run `poetry update` for the lockfile (that took 2026.9s, but it was working on its own)

**Comment by scarlehoff** [comment]
Numerical results seems to be unchanged. I would say we merge.

**Pull request merged**
