### PR TITLE
Move pinefarm out

### PR DESCRIPTION
**Pull request by AleCandido**
I just moved everything to https://github.com/NNPDF/pinefarm

I kept here just the pinecards top-level, and a minimal `README.md` (feel free to improve it).

### CODE REVIEW

**Comment by scarlehoff** [comment]
Can PR be transferred using the github site? I guess they need to be repushed, rebased or whatever the term is.

**Comment by AleCandido** [comment]
> Can PR be transferred using the github site? I guess they need to be repushed, rebased or whatever the term is.

I believe you can't, because it is a completely different Git repo, not even a fork.
You can open a new PR, from this repo targeting that one, but I'm not sure if you can do it if it's not a fork.

At the bare Git level, it is cumbersome as well, but you can take an instance of this repo, add `pinefarm` as a remote, push the branch there, and open the PR. I'm what is the easiest option.

**Review by felixhekhorn — APPROVED** [review]

**Comment by felixhekhorn** [comment]
> I can transfer issues, and I will do, but I can not transfer PRs. However, the only two PRs that are related to `pinefarm` (as opposed to just providing/fixing pinecards themselves) are #166 #159, they will have to be moved manually.

also https://github.com/NNPDF/runcards/pull/161 has to be moved

**Comment by scarlehoff** [comment]
Shouldn't we merge this?

**Comment by AleCandido** [comment]
> Shouldn't we merge this?

I was waiting for full approval, i.e. at least you @scarlehoff and @cschwan. (If you wish also you @andreab1997, but you worked little in here, so you don't have to)

**Review by scarlehoff — APPROVED** [review]

**Review by cschwan — APPROVED** [review]

**Pull request merged**
